---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u chethanarjun@gmail.com -p Chethankumar@123 softlabs.jfrog.io  
    
    - name: pull an image
      shell: docker pull softlabs.jfrog.io/sample-war-app/sample_docker_image_with_war_deploy:v1.0-{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 softlabs.jfrog.io/sample-war-app/sample_docker_image_with_war_deploy:v1.0-{{ build_number }}
 
   
